name: Docker Build and Run

on:
  push:
    branches:
      - dev

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Load and export variables from .env file
        run: |
          export $(grep -v '^#' .env | xargs)
        shell: bash

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t minicran -f Dockerfile_ubuntu .

      - name: Run Docker container
        run: |
          docker run -v C:/chinapat.onp/source/R_research_package/miniCRAN:/miniCRAN \
          -e R_VERSION_DATE="$R_VERSION_DATE" \
          --env-file=$ENV_FILE \
          minicran
        shell: bash
