name: Docker Build and Run

on:
  push:
    branches:
      - dev

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t minicran -f Dockerfile_ubuntu .

      - name: Run Docker container via bash script
        run: |
            
            ./run_docker.sh
