name: Docker Build and Run

on:
  push:
    branches:
      - dev

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Verify .env file exists
        run: |
          if [ ! -f .env ]; then echo ".env file not found"; exit 1; fi
        shell: bash

      - name: Load .env file
        run: |
          set -o allexport
          source .env
          set +o allexport
        shell: bash

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t minicran -f Dockerfile_ubuntu .

      - name: Run Docker container
        run: |
          docker run -v C:/chinapat.onp/source/R_research_package/miniCRAN:/miniCRAN \
          -e R_VERSION_DATE="$R_VERSION_DATE" \
          --env-file=$ENV_FILE \
          minicran
        shell: bash
